// Sistema de Gestão de Pendências Imobiliárias v1.0
// Dados de exemplo para demonstração

let pendenciasData = [
    {id_unidade:"APT-302A",cliente:"João Silva",unidades:1,colaborador:"Barbara",data_inclusao:"2025-01-15",data_escrituracao:null,canal:"WhatsApp",contatos:3,ultima_atualizacao:"2025-01-21 14:30"},
    {id_unidade:"APT-405B",cliente:"Maria Souza",unidades:2,colaborador:"Cicero",data_inclusao:"2025-01-10",data_escrituracao:"2025-01-22",canal:"E-mail",contatos:5,ultima_atualizacao:"2025-01-22 09:15"},
    {id_unidade:"APT-501C",cliente:"Pedro Costa",unidades:1,colaborador:"Marina",data_inclusao:"2024-12-20",data_escrituracao:null,canal:"Telefone",contatos:8,ultima_atualizacao:"2025-01-20 16:45"},
    {id_unidade:"APT-203D",cliente:"Ana Lima",unidades:3,colaborador:"Roberto",data_inclusao:"2024-12-05",data_escrituracao:null,canal:"WhatsApp",contatos:2,ultima_atualizacao:"2025-01-15 11:20"},
    {id_unidade:"APT-308E",cliente:"Carlos Mendes",unidades:1,colaborador:"Felipe",data_inclusao:"2025-01-08",data_escrituracao:"2025-01-18",canal:"E-mail",contatos:4,ultima_atualizacao:"2025-01-18 10:00"},
    {id_unidade:"APT-602F",cliente:"Beatriz Oliveira",unidades:2,colaborador:"Juliana",data_inclusao:"2025-01-12",data_escrituracao:null,canal:"WhatsApp",contatos:1,ultima_atualizacao:"2025-01-19 13:30"},
    {id_unidade:"APT-104G",cliente:"Ricardo Santos",unidades:1,colaborador:"Barbara",data_inclusao:"2024-11-25",data_escrituracao:null,canal:"Telefone",contatos:6,ultima_atualizacao:"2025-01-08 09:00"},
    {id_unidade:"APT-706H",cliente:"Fernanda Lima",unidades:2,colaborador:"Cicero",data_inclusao:"2025-01-05",data_escrituracao:null,canal:"WhatsApp",contatos:3,ultima_atualizacao:"2025-01-21 15:45"},
    {id_unidade:"APT-503I",cliente:"Gustavo Pereira",unidades:1,colaborador:"Marina",data_inclusao:"2024-12-28",data_escrituracao:"2025-01-20",canal:"E-mail",contatos:7,ultima_atualizacao:"2025-01-20 14:20"},
    {id_unidade:"APT-301J",cliente:"Lucia Martins",unidades:1,colaborador:"Roberto",data_inclusao:"2025-01-02",data_escrituracao:null,canal:"WhatsApp",contatos:2,ultima_atualizacao:"2025-01-21 10:15"}
];

const colaboradores=["Barbara","Cicero","Marina","Roberto","Felipe","Juliana"];
let currentPage=1;let rowsPerPage=25;let sortColumn=-1;let sortDirection='asc';
let statusChart=null;let colaboradorChart=null;let temporalChart=null;let individualChart=null;

function calculateDaysElapsed(a,b){const c=new Date,d=new Date(a);return b?Math.floor((new Date(b)-d)/(1e3*60*60*24)):Math.floor((c-d)/(1e3*60*60*24))}
function calculateStatus(a,b){return b?"Concluído":a>30?"Crítico":a>15?"Atenção":"Em Andamento"}
function getStatusClass(a){return{Concluído:"status-completed","Em Andamento":"status-in-progress",Atenção:"status-attention",Crítico:"status-critical"}[a]||""}
function formatDate(a){return a?(new Date(a)).toLocaleDateString("pt-BR"):"-"}
function showToast(a,b="success"){const c=document.getElementById("toast");c.textContent=a;c.className=`toast show ${b}`;setTimeout(()=>{c.className="toast"},3e3)}

function init(){updateDateTime();setInterval(updateDateTime,1e3);setupTabs();populateColaboradorFilters();loadDashboard()}
function updateDateTime(){const a=new Date,b={weekday:"long",year:"numeric",month:"long",day:"numeric",hour:"2-digit",minute:"2-digit"};document.getElementById("currentDateTime").textContent=a.toLocaleDateString("pt-BR",b)}

function setupTabs(){document.querySelectorAll(".tab-btn").forEach(a=>{a.addEventListener("click",()=>{const b=a.dataset.tab;document.querySelectorAll(".tab-btn").forEach(a=>a.classList.remove("active"));a.classList.add("active");document.querySelectorAll(".tab-content").forEach(a=>a.classList.remove("active"));document.getElementById(b).classList.add("active");"dashboard"===b?loadDashboard():"database"===b?loadDatabase():"individual"===b?loadIndividualPerformance():"temporal"===b&&loadTemporalReport()})})}

function populateColaboradorFilters(){const a=document.getElementById("filterColaborador"),b=document.getElementById("selectColaborador");colaboradores.forEach(c=>{const d=document.createElement("option");d.value=c;d.textContent=c;a.appendChild(d);const e=document.createElement("option");e.value=c;e.textContent=c;b.appendChild(e)})}

function loadDashboard(){updateKPIs();renderStatusChart();renderColaboradorChart();renderTemporalEvolutionChart();renderCriticalAlertsTable()}

function updateKPIs(){const a=pendenciasData.filter(a=>!a.data_escrituracao).length,b=pendenciasData.filter(a=>{const b=calculateDaysElapsed(a.data_inclusao,a.data_escrituracao);return!a.data_escrituracao&&b>30}).length,c=new Date,d=new Date(c.getFullYear(),c.getMonth(),1),e=pendenciasData.filter(a=>{if(!a.data_escrituracao)return!1;return new Date(a.data_escrituracao)>=d}).length,f=pendenciasData.length,g=pendenciasData.filter(a=>a.data_escrituracao).length,h=f>0?Math.round(g/f*100):0;document.getElementById("totalActive").textContent=a;document.getElementById("totalCritical").textContent=b;document.getElementById("totalCompleted").textContent=e;document.getElementById("completionRate").textContent=h+"%"}

function renderStatusChart(){const a=document.getElementById("statusChart").getContext("2d"),b={};pendenciasData.forEach(a=>{const c=calculateDaysElapsed(a.data_inclusao,a.data_escrituracao),d=calculateStatus(c,a.data_escrituracao);b[d]=(b[d]||0)+1});statusChart&&statusChart.destroy();statusChart=new Chart(a,{type:"pie",data:{labels:Object.keys(b),datasets:[{data:Object.values(b),backgroundColor:["#00AA00","#0066CC","#FFAA00","#FF0000","#808080"]}]},options:{responsive:!0,maintainAspectRatio:!1,plugins:{legend:{position:"bottom"}}}})}

function renderColaboradorChart(){const a=document.getElementById("colaboradorChart").getContext("2d"),b={};colaboradores.forEach(a=>{b[a]=pendenciasData.filter(b=>b.colaborador===a&&!b.data_escrituracao).length});colaboradorChart&&colaboradorChart.destroy();colaboradorChart=new Chart(a,{type:"bar",data:{labels:Object.keys(b),datasets:[{label:"Pendências Ativas",data:Object.values(b),backgroundColor:"#1FB8CD"}]},options:{responsive:!0,maintainAspectRatio:!1,indexAxis:"y",plugins:{legend:{display:!1}},scales:{x:{beginAtZero:!0}}}})}

function renderTemporalEvolutionChart(){const a=document.getElementById("temporalChart").getContext("2d"),b=[],c=[];for(let a=29;a>=0;a--){const d=new Date;d.setDate(d.getDate()-a);b.push(d.toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit"}));const e=pendenciasData.filter(b=>{const c=new Date(b.data_inclusao);return c<=d&&(!b.data_escrituracao||new Date(b.data_escrituracao)>d)}).length;c.push(e)}temporalChart&&temporalChart.destroy();temporalChart=new Chart(a,{type:"line",data:{labels:b,datasets:[{label:"Pendências Abertas",data:c,borderColor:"#1FB8CD",backgroundColor:"rgba(31, 184, 205, 0.1)",fill:!0,tension:.4}]},options:{responsive:!0,maintainAspectRatio:!1,plugins:{legend:{display:!1}},scales:{y:{beginAtZero:!0}}}})}

function renderCriticalAlertsTable(){const a=document.getElementById("criticalAlertsTable");a.innerHTML="";const b=pendenciasData.map(a=>({...a,dias:calculateDaysElapsed(a.data_inclusao,a.data_escrituracao),status:calculateStatus(calculateDaysElapsed(a.data_inclusao,a.data_escrituracao),a.data_escrituracao)})).filter(a=>!a.data_escrituracao).sort((a,b)=>b.dias-a.dias).slice(0,10);b.forEach(b=>{const c=document.createElement("tr");b.dias>30&&c.classList.add("status-critical");c.innerHTML=`<td>${b.id_unidade}</td><td>${b.cliente}</td><td>${b.colaborador}</td><td>${b.dias}</td><td><span class="${getStatusClass(b.status)}">${b.status}</span></td>`;a.appendChild(c)})}

function loadDatabase(){const a=document.getElementById("databaseTable");a.innerHTML="";const b=(currentPage-1)*rowsPerPage,c=b+rowsPerPage;pendenciasData.slice(b,c).forEach(b=>{const c=calculateDaysElapsed(b.data_inclusao,b.data_escrituracao),d=calculateStatus(c,b.data_escrituracao),e=document.createElement("tr");e.innerHTML=`<td>${b.id_unidade}</td><td>${b.cliente}</td><td>${b.unidades}</td><td>${b.colaborador}</td><td>${formatDate(b.data_inclusao)}</td><td>${formatDate(b.data_escrituracao)}</td><td>${c}</td><td><span class="${getStatusClass(d)}">${d}</span></td><td>${b.canal}</td><td>${b.contatos}</td><td>${b.ultima_atualizacao}</td>`;a.appendChild(e)});document.getElementById("pageInfo").textContent=`Página ${currentPage}`;document.getElementById("prevBtn").onclick=()=>{currentPage>1&&(currentPage--,loadDatabase())};document.getElementById("nextBtn").onclick=()=>{currentPage<Math.ceil(pendenciasData.length/rowsPerPage)&&(currentPage++,loadDatabase())};document.getElementById("exportBtn").onclick=()=>{let a="ID Unidade,Cliente,Unidades,Colaborador,Data Inclusão,Data Escrituração,Dias,Status,Canal,Contatos,Última Atualização\n";pendenciasData.forEach(b=>{const c=calculateDaysElapsed(b.data_inclusao,b.data_escrituracao),d=calculateStatus(c,b.data_escrituracao);a+=`${b.id_unidade},${b.cliente},${b.unidades},${b.colaborador},${formatDate(b.data_inclusao)},${formatDate(b.data_escrituracao)},${c},${d},${b.canal},${b.contatos},${b.ultima_atualizacao}\n`});const c=new Blob([a],{type:"text/csv"}),d=URL.createObjectURL(c),e=document.createElement("a");e.href=d;e.download="pendencias-report.csv";e.click()}}

function loadIndividualPerformance(){const a=document.getElementById("selectColaborador").value;if(!a)return;const b=pendenciasData.filter(b=>b.colaborador===a),c=b.filter(a=>!a.data_escrituracao),d=b.filter(a=>a.data_escrituracao).length,e=b.length>0?Math.round(d/b.length*100):0,f=b.map(a=>calculateDaysElapsed(a.data_inclusao,a.data_escrituracao)).reduce((a,b)=>a+b,0)/(b.length||1),g=c.filter(a=>calculateDaysElapsed(a.data_inclusao,a.data_escrituracao)>30).length;document.getElementById("indTotalAssigned").textContent=b.length;document.getElementById("indCompletionRate").textContent=e+"%";document.getElementById("indAvgTime").textContent=Math.round(f)+" dias";document.getElementById("indCritical").textContent=g;const h=document.getElementById("individualTable");h.innerHTML="";c.forEach(a=>{const b=calculateDaysElapsed(a.data_inclusao,a.data_escrituracao),c=calculateStatus(b,a.data_escrituracao),d=document.createElement("tr");d.innerHTML=`<td>${a.id_unidade}</td><td>${a.cliente}</td><td>${b}</td><td><span class="${getStatusClass(c)}">${c}</span></td><td>${a.contatos}</td>`;h.appendChild(d)})}

function loadTemporalReport(){const a=document.getElementById("temporalPeriod").value,b=document.getElementById("temporalTable");b.innerHTML="";for(let c=0;c<4;c++){const d=new Date;d.setDate(d.getDate()-7*c);const e=new Date(d);e.setDate(e.getDate()-7);const f=pendenciasData.filter(a=>{const b=new Date(a.data_escrituracao||"2099-12-31");return b>=e&&b<=d}).length,g=pendenciasData.filter(a=>{if(!a.data_escrituracao)return!1;const b=new Date(a.data_escrituracao);return b>=e&&b<=d}).length,h=pendenciasData.filter(a=>{const b=calculateDaysElapsed(a.data_inclusao,a.data_escrituracao);return!a.data_escrituracao&&b>30?b<=d&&b>=e:!1}).length,i=f>0?Math.round(g/f*100):0,j=document.createElement("tr");j.innerHTML=`<td>${e.toLocaleDateString("pt-BR")} a ${d.toLocaleDateString("pt-BR")}</td><td>${g}</td><td>20</td><td>${h}</td><td>${i}%</td>`;b.appendChild(j)}}

document.addEventListener("DOMContentLoaded",init);